### ISSUE TITLE
IE11: social media icon size

### ISSUE THREAD

**Issue by yellowled** [yellowled/blog-theme#19]
In IE11, the social media icons in the footer are displayed too small although the IE devtools show that the CSS size is calculated properly (30x30px in larger resolutions, set in `rem`). This does **not** happen for other icons from the same SVG sprite (hamburger, pagination arrows), so it must be specific to the CSS(?) of the social media icons or the layout of the containing elements …?

**Comment by kosmar** [comment]
you might want to check width and viewbox values in all your svgs. some are very large, some are <30

**Comment by yellowled** [comment]
That seems to be a good point to start at least, thanks. You are right:
- the original social icons have pretty small view boxes
- the other icon's originals (which come from FontAwesomeSVG) have huge view boxes
- these are both carried over correctly to the SVG sprite
- but for some reason, they are _not_ correct for the social icons in the markup

**Comment by yellowled** [comment]
Confirmed in IE11 – with proper `viewbox` values in the markup, it works. Not sure why I got that wrong or mixed up, but thanks again!
